swagger: '2.0'
info:
  version: "1.0.0"
  title: "API de Produtos"
  description: "Documentação da API para gerenciamento de produtos"
host: "localhost:8000"
basePath: "/v1"
schemes:
  - "https"
  - "http"
tags:
  - name: "products"
    description: "Operações de produtos"
paths:
  /products:
    get:
      tags:
        - "products"
      summary: "Lista todos os produtos"
      description: "Retorna uma lista de todos os produtos"
      responses:
        200:
          description: "Lista de produtos"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
    post:
      tags:
        - "products"
      summary: "Cria um novo produto"
      description: "Adiciona um novo produto à lista"
      parameters:
        - in: "body"
          name: "body"
          description: "Objeto de produto que precisa ser adicionado"
          required: true
          schema:
            $ref: "#/definitions/ProductInput"
      responses:
        201:
          description: "Produto criado"
        400:
          description: "Requisição inválida"
  /products/{ProductId}:
    get:
      tags:
        - "products"
      summary: "Obtém um produto pelo ID"
      description: "Retorna um único produto com base no ID fornecido"
      parameters:
        - name: "ProductId"
          in: "path"
          description: "ID do produto que precisa ser recuperado"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "Produto encontrado"
          schema:
            $ref: "#/definitions/Product"
        404:
          description: "Produto não encontrado"
definitions:
  Product:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      price:
        type: "number"
        format: "float"
  ProductInput:
    type: "object"
    properties:
      name:
        type: "string"
        example: "Arroz"
      price:
        type: "number"
        format: "float"
        example: 20.20
